import { GitHubLogoIcon } from "@radix-ui/react-icons";
import {
  BookIcon,
  Brain,
  BrainIcon,
  EyeIcon,
  EyeOffIcon,
  HomeIcon,
  ListIcon,
  Loader2Icon,
  LogOutIcon,
  Pyramid,
  Shell,
  User2Icon,
  Users,
} from "lucide-react";
export const Icons = {
  logo: Brain,
  github: GitHubLogoIcon,
  spinner: Loader2Icon,
  eye: EyeIcon,
  eyeOff: EyeOffIcon,
  pyramid: Pyramid,
  shell: Shell,
  brainCog: Brain,
  loader2: Loader2Icon,
  book: BookIcon,
  brain: BrainIcon,
  home: HomeIcon,
  list: ListIcon,
  logOut: LogOutIcon,
  user2: User2Icon,
  users: Users,
};
